Friend fragment
swift-wallet/sdp2022 pull request #129
Opened 2022-04-07 15:34 UTC by andrew880

2022-04-08 08:03 UTC, ahominal requested changes
There is still no test in this pull request ... Please make some at least for the UI

2022-04-08 08:39 UTC, 0xdieman commented on app/src/androidTest/java/com/sdp/swiftwallet/UiTest/MessageFragmentTest.java
> +    }
Isn't there a line missing ?

2022-04-08 08:39 UTC, 0xdieman commented on app/src/main/java/com/sdp/swiftwallet/presentation/friend/fragments/FriendItem.java
> +//    }
I think you could directly remove that

2022-04-08 08:39 UTC, 0xdieman commented on app/src/main/java/com/sdp/swiftwallet/presentation/main/fragments/MessageFragment.java
> +    private FirebaseAuth mAuth;
You should be able to use hilt injection for this instance, at least for the next weeks

2022-04-08 08:39 UTC, 0xdieman commented on app/src/main/java/com/sdp/swiftwallet/presentation/main/fragments/MessageFragment.java
> +            ((TextView)view.findViewById(R.id.addFriendStatus)).setText("Cannot Add Yourself");
Those hardcoded strings would fit better in the values/strings file

2022-04-28 17:10 UTC, ahominal commented
any update Andrew?

2022-04-28 17:11 UTC, 0xdieman commented on app/src/main/java/com/sdp/swiftwallet/presentation/main/fragments/MessageFragment.java
> +            ((TextView)view.findViewById(R.id.addFriendStatus)).setText("Cannot Add Yourself");
I think

2022-04-28 22:52 UTC, Zotchh commented
Closing the PR on this branch for now because it is outdated

2022-04-28 22:52 UTC, closed without merging